export const RECEIVE_USER_INFO = 'receive_user_info'
export const LOGOUT = 'logout'
export const RECEIVE_CATEGORYS = 'receive_categorys'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_ADDRESS = 'receive_address'
